import jsPDF from 'jspdf'
import type { AnalysisResult } from '@/types'

export function generateAnalysisPDF(result: AnalysisResult, productUrl: string, productName?: string): Blob {
  const doc = new jsPDF()
  const pw = doc.internal.pageSize.getWidth()
  const ph = doc.internal.pageSize.getHeight()
  let y = 20

  function header(s: string) {
    y += 4
    doc.setFontSize(14)
    doc.setTextColor(26, 86, 219)
    doc.text(s, 20, y)
    y += 2
    doc.setDrawColor(26, 86, 219)
    doc.setLineWidth(0.5)
    doc.line(20, y, pw - 20, y)
    y += 8
  }

  function body(text: string) {
    doc.setFontSize(10)
    doc.setTextColor(15, 23, 42)
    const lines = doc.splitTextToSize(text, 170)
    for (const line of lines) {
      if (y > ph - 25) { doc.addPage(); y = 20 }
      doc.text(line, 20, y)
      y += 5.5
    }
    y += 4
  }

  function bulletList(items: string[]) {
    doc.setFontSize(10)
    doc.setTextColor(15, 23, 42)
    for (const item of items) {
      if (y > ph - 25) { doc.addPage(); y = 20 }
      doc.text(`\u2022 ${item}`, 22, y)
      y += 6
    }
    y += 4
  }

  // Page 1: Cover
  doc.setFillColor(12, 27, 51)
  doc.rect(0, 0, pw, 120, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(28)
  doc.text('ProductScope', pw / 2, 50, { align: 'center' })
  doc.setFontSize(18)
  doc.setTextColor(245, 158, 11)
  doc.text('Product Analysis Report', pw / 2, 70, { align: 'center' })
  doc.setFontSize(10)
  doc.setTextColor(200, 200, 200)
  const date = new Date(result.completed_at ?? result.created_at).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  doc.text(date, pw / 2, 90, { align: 'center' })
  if (productName) {
    doc.text(productName, pw / 2, 102, { align: 'center' })
  }

  // URL
  y = 140
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text('Product URL:', 20, y)
  y += 5
  doc.setTextColor(26, 86, 219)
  doc.text(productUrl, 20, y)
  y += 12

  // Sections
  if (result.product_description) {
    header('Product Description')
    body(result.product_description)
  }

  if (result.ad_headlines?.length) {
    header('Ad Headlines')
    bulletList(result.ad_headlines)
  }

  if (result.marketing_hooks?.length) {
    header('Marketing Hooks')
    bulletList(result.marketing_hooks)
  }

  if (result.strengths?.length) {
    header('Strengths')
    bulletList(result.strengths)
  }

  if (result.weaknesses?.length) {
    header('Weaknesses')
    bulletList(result.weaknesses)
  }

  if (result.target_audience) {
    header('Target Audience')
    body(result.target_audience)
  }

  if (result.main_objection) {
    header('Main Objection')
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    const objLines = doc.splitTextToSize(`"${result.main_objection}"`, 170)
    for (const line of objLines) {
      if (y > ph - 25) { doc.addPage(); y = 20 }
      doc.text(line, 20, y)
      y += 5.5
    }
    y += 4

    header('Objection Response')
    body(result.objection_response ?? '')
  }

  // Footer
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 180)
    doc.text(`Page ${i} of ${pages}`, pw / 2, ph - 10, { align: 'center' })
    doc.text('Generated by ProductScope', pw / 2, ph - 5, { align: 'center' })
  }

  return doc.output('blob')
}
